#!/usr/bin/env ruby

# Requires:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
require "sinatra"
require "slim"

# Application::::::::::::::::::::::::::::::::::::::::::::::::::::::::
class MyApp < Sinatra::Base
  get "/" do
    slim :index
  end
  post "/endpoint" do
    slim :endpoint
  end
end

MyApp.run! :port => 4567
